// <auto-generated />
namespace CIS174GameProject.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RedoDatabaseCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RedoDatabaseCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201904020146493_Redo-Database-Creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
